### PR TITLE
Fix traefik version to 1.2.1

### PR DESCRIPTION
**Pull request by sapk**
Since v1.2.2 seems to introduce a redirect loop (302).

The *.gitea.io websites are inaccessible since a little time due to a redirect loop.

I suspect that it is the same bug that : containous/traefik#1429.

I have the same problem on one of my server and fixing to v1.2.1 fix the it.

### CODE REVIEW

**Comment by lunny** [comment]
LGTM

**Comment by andreynering** [comment]
Thank you @sapk 

Trusted LGTM

Will this be automatically deployed after merge?

**Review by appleboy — APPROVED** [review]

**Comment by appleboy** [comment]
LGTM

**Comment by sapk** [comment]
L-G-T-M must be blocked because of the same problem ^^.

**Comment by lunny** [comment]
So I use my admin to do that. And @andreynering I don't know if it could be automatically deployed.

**Comment by sapk** [comment]
A fix is already proposed for this bug in traefik. I will follow and revert back to :latest when fix is applied and docker image rebuild.

**Comment by plessbd** [comment]
This has been resolved now.

**Pull request merged**
