### PR TITLE
Switched to our LGTM container

### PR DESCRIPTION
**Pull request by tboerger**
Signed-off-by: Thomas Boerger <thomas@webhippie.de>

### CODE REVIEW

**Comment by strk** [comment]
LGTM (if needed)

**Comment by tboerger** [comment]
Since I have already applied it you can see that the auto labeling works ;)

**Comment by strk** [comment]
Great! Is there any way to also get those labels addition events attributed to a "bot" user ?

**Comment by lunny** [comment]
LGTM

**Comment by lunny** [comment]
It seems `lgtm/need 1` has not been removed.

**Comment by tboerger** [comment]
Maybe a big within the lgtm implementation?

**Comment by lunny** [comment]
I will review the code.

**Pull request merged**
