### PR TITLE
Remove old keys and users

### PR DESCRIPTION
**Pull request by lafriks**
As title.

### CODE REVIEW

**Review by techknowlogick — APPROVED** [review]

**Comment by lafriks** [comment]
@techknowlogick you forgot to add your user to `users_available:` section

**Comment by lunny** [comment]
@lafriks I think we could give some rights to managers not only the owners.

**Review by jonasfranz — APPROVED** [review]

**Comment by jonasfranz** [comment]
@lunny maybe create another PR with this change?

**Comment by lafriks** [comment]
@lunny I don't think that is needed

**Pull request merged**
