### PR TITLE
Update traefik to latest stable (v1.4.5)

### PR DESCRIPTION
**Pull request by bkcsoft**

### CODE REVIEW

**Comment by lafriks** [comment]
LGTM

**Comment by lunny** [comment]
Why remove `containous/`?

**Comment by tboerger** [comment]
> Why remove containous/?

Because it won't get pished there anymore, you have to use library/traefik for more current versions.

**Review by tboerger — APPROVED** [review]

**Comment by tboerger** [comment]
LGTM

**Pull request merged**
