### PR TITLE
Update traefik v1.2.3

### PR DESCRIPTION
**Pull request by sapk**
Remove temporary fixed version (#15) because of a bug in traefik

### CODE REVIEW

**Comment by tboerger** [comment]
I would suggest to keep a fixed version to avoid issues like that in the future.

**Comment by sapk** [comment]
Ok I update to last 1.2.x branch so. The next version will be 1.3.x.

**Comment by lunny** [comment]
LGTM

**Review by tboerger — APPROVED** [review]

**Comment by tboerger** [comment]
LGTM

**Pull request merged**
