### PR TITLE
Add more pubkeys to server

### PR DESCRIPTION
**Pull request by bkcsoft**
I have more than 1 computer :trollface:

### CODE REVIEW

**Comment by tboerger** [comment]
Than also add it to https://github.com/go-gitea/infrastructure/blob/master/ansible/group_vars/all.yml#L3

**Comment by bkcsoft** [comment]
@tboerger should I relaly do that? I don't wanna log in as root 😆

**Comment by tboerger** [comment]
We can drop that when I have configured sudo 8)

**Comment by strk** [comment]
LGTM

**Comment by bkcsoft** [comment]
no sudo?! 😱

**Comment by tboerger** [comment]
I have not configured it explicitly. Try it :)

**Comment by bkcsoft** [comment]
@tboerger done :)

**Comment by tboerger** [comment]
LGTM

**Pull request merged**
