### PR TITLE
/usr/bin/grep doesnt exist, fixed that

### PR DESCRIPTION
**Pull request by tboerger**

### CODE REVIEW

**Comment by lunny** [comment]
On mac, `/usr/bin/grep` is correct.

**Comment by tboerger** [comment]
But this is not running on the mac, this is only running on our Ubuntu 16.04 machine, and there it's /bin/grep.

**Comment by strk** [comment]
I would not specify full path and rely on $PATH instead, but anyway LGTM

**Comment by tboerger** [comment]
> I would not specify full path and rely on $PATH instead, but anyway LGTM

Than you don't know systemd, These commands MUST be specified with full path.

**Pull request merged**
