### PR TITLE
Add `kind/api` to Label-list

### PR DESCRIPTION
**Pull request by bkcsoft**
@tboerger only a month late or so 😂

### CODE REVIEW

**Review by appleboy — APPROVED** [review]

**Comment by lunny** [comment]
LGTM

**Comment by lunny** [comment]
@appleboy you have to comment L-G-T-M so that the robot could detect it.

**Comment by appleboy** [comment]
@lunny Apologies. I forgot to do it. LGTM

**Comment by lunny** [comment]
@appleboy if we can send a PR to go-gitea/lgtm to also detect github's review, it's also OK.

**Pull request merged**
